<?php

namespace AppBundle\Repository;

/**
 * EscolaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscolaRepository extends \Doctrine\ORM\EntityRepository
{
}
